name: soepy
channels:
  - defaults
  - conda-forge
dependencies:
- numpy
- numba
- scipy
- pandas
- python==3.13
- flake8
- pytest
- pytest-cov
- pandoc
- pyyaml
- nbsphinx
- sphinx_rtd_theme
- codecov
- ipython
- pip
- pip:
  - pre-commit
  - black
  - jax
  - jaxlib
